meta:
  title:
  thumbnail:
  description:
  sns:
    - twitter
slide:
  showIndex: true
  code:
    languages:
      - yaml
      - json
      - markdown
      - javascript
      - css
extends:
  css: style.css
